### ISSUE TITLE
[Bug] No audio on macOS Big Sur

### ISSUE THREAD

**Issue by ThatsNiceGuy** [etternagame/etterna#1015]
**Describe the bug**
There is no audio played anywhere. Not in gameplay, not in menus, etc

**To Reproduce**
not sure, just happens on my machine

**Expected behavior**
audio playback

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - MacBook Pro 15" 2018 (T2, i7-8850H, Radeon Pro 560X)
 - Etterna 0.70.4
 - 64bit

**Additional context**

When launching from Terminal, I see the following line printed:
```Couldn't load driver AudioUnit: Failed to set render callback: '???D' (4294900548).```

**Comment by jameskr97** [comment]
Took a look at this one. It's an error at `RageSoundDrive_AU.cpp:175`. When this is run
```cpp
error = AudioUnitSetProperty(m_OutputUnit,
    kAudioUnitProperty_SetRenderCallback,
    kAudioUnitScope_Input,
    0,
    &input,
    sizeof(input));
``` 
it returns a `kAudioComponentErr_NotPermitted` error, which means the audio callback function wasn't registered. I looked around, and saw this information about that error (written right next to where it's defined:
```cpp
/**
    @constant   kAudioComponentErr_NotPermitted
		app needs "inter-app-audio" entitlement or host app needs "audio" in its UIBackgroundModes.
		Or app is trying to register a component not declared in its Info.plist.
**/
```

Some googling led me to (1) [here](https://stackoverflow.com/questions/20145360/error-from-registration-server-when-publishing-audio-unit), (2) [here](https://www.gitmemory.com/issue/FluidSynth/fluidsynth/803/808712435), and (3) [here](https://gist.github.com/xorrior/2b2bd5a95999c431f0bdc232f14d1db9).

1 and 2 both suggested it was an `Info.plist` permissions issue, and 3 gave an example what what those permissions might have to look like. Since we use CMake, we have to make a `MacOSXBundleInfo.plist.in` in our `cmake/Modules` (which you can copy from `<cmake_install_prefix>/Modules/MacOSXBundleInfo.plist.in`), though attempting to add the keys didn't work, and I couldn't find much documentation on Apple's website on how exactly components can be declared in an `Info.plist`.

Still working on this, but writing this as a note so I know where I've gotten so far.

**Comment by bluebandit21** [comment]
My googling lead me to https://developer.apple.com/documentation/bundleresources/entitlements/inter-app-audio?language=objc which may be relevant. 
This might be an entitlements.plist issue, if it were.

**Comment by bluebandit21** [comment]
The fix was determined by noticing the following warning in XCode when running:
```This application, or a library it uses, is using the deprecated Component Manager for hosting Audio Components. This is not supported when rebuilding against the 11.00 or later SDK. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.```

**Comment by jameskr97** [comment]
Also note: That only shows in Xcode. I usually compile via CLI (Ninja or Makefiles), and that warning did not show.

**Comment by poco0317** [comment]
#1025
