### ISSUE TITLE
Im new to eternia and it wont let me download the songs or packs if they just wont download 

### ISSUE THREAD

**Issue by userasde** [etternagame/etterna#1063]
**Describe the bug**

**To Reproduce**
1. Go to 'start menu without songs'
2. Click on 'any of the first packs that show up'
3. Scroll down to 'nothing'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows]
 - Version [10]
 - 64bit 

**Additional context**

**Comment by poco0317** [comment]
Core bundles are buggy in the release build because download traffic to the links they point to is too high for the host. This will be fixed in the next release.

For now to download a bundle, go directly to the pack downloader, then click bundle select. Click a bundle, then click the download button on each pack that shows up. Do not press the download all button. Do not click any bundles in the "you have no songs" screen.
