### ISSUE TITLE
[Feature Request]: Sort by Block-Level

### ISSUE THREAD

**Issue by Lucien0001** [etternagame/etterna#1131]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

Add the ability to sort by the block level assigned by the stepauthor. 

### How Does The Feature Add To The Game?

Certain packs are designed with block levels being taken into account (especially packs designed for pad) to make it easier for players to find charts at their level. Adding the ability to sort by block levels would make it easier for players to utilize this feature.

### Additional Context

Multi-difficulty charts would need to be accounted for when making this feature in a way that properly displays them.

**Comment by poco0317** [comment]
this makes no sense because the packs that do this usually utilize the quirks of the "alphabetical" sorting system to get them to sort the correct way
so i added the sortmode anyways which effectively made no difference
maybe you gave way too little information
8c261528f7bf16f009c2570763af488954e2f39d
