### ISSUE TITLE
[Bug]: If a folder is named like a file with an extension, the game behaves in various strange ways depending on said extension

### ISSUE THREAD

**Issue by velaachlorine** [etternagame/etterna#1147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version Info

Latest available release

### What operating system are you seeing the problem on?

Windows

### Bug Behavior

if a folder is named with an audio file extension (.mp3 .ogg .wav) the game crashes with no message on launch at the "loading songs from disk" stage
![image](https://user-images.githubusercontent.com/53107421/158182161-6e387f6a-02d5-4be1-a5c5-ab4f92f24ed2.png)
this also happens if there's an actual audio file loose inside a pack like this
![image](https://user-images.githubusercontent.com/53107421/158184719-ac9c30cd-ea0a-4a93-91b0-d0337025f208.png)

if a folder is named with an image extension (.png .jpg) the game tries to load it as the pack banner which doesn't crash it but it doesn't like it either
![image](https://user-images.githubusercontent.com/53107421/158182778-81cbdfc8-4a1f-4654-8664-a2fb74fd63d3.png)

if a folder is named with .sm however, it loads fine

**Comment by nico-abram** [comment]
If anyone wants to try to fix this, a good starting point is probably Song.cpp around here:

https://github.com/etternagame/etterna/blob/a781a509decc8f9653c09ca7f4f4280d6b988a8d/src/Etterna/Models/Songs/Song.cpp#L586-L592


We've got `FILEMAN->IsADirectory` and `FILEMAN->IsAFile` which I think we can use here since fileman is [initialized before song loading starts](https://github.com/etternagame/etterna/blob/develop/src/Etterna/Globals/StepMania.cpp#L992-L993)

Not sure if it'd be better to add a parameter for "only files" to GetDirListing (Or maybe change the boolean to an enum with values like NO_FILTER, ONLY_FILES, ONLY_DIRS )

**Comment by poco0317** [comment]
fixed all of the mentioned issues 71991a707c6037485873bb6c79cc04182239bee5
this probably doesnt break anything... maybe.... lets find out.
