### ISSUE TITLE
rich presence and breakdown

### ISSUE THREAD

**Issue by Zoqos** [etternagame/etterna#119]
i've recently updated to 57.1
discord's rich presence does not work.
next, chordjack and jacks are still labeled as jackspeed.
if there is something to do fix this hmu

**Comment by TheROPFather** [comment]
Very useful report, thanks.

Would it be too much to ask for uh, and operating system?

**Comment by DDMythical** [comment]
Sounds like it hasn't even updated

what does it say at the bottom right in regards to version

**Comment by Zoqos** [comment]
@DDMythical 57.1

**Comment by Zoqos** [comment]
@TheROPFather win 10

**Comment by Nickito12** [comment]
Hello! I think you can probably see how the initial report cant be very helpful (If we cant reproduce something its pretty hard to help you, specially with this little information)
Could you try reinstalling in another location (Like Games/Etterna2 or something) and checking if the problem persists?
If so, I'd apprecciate it if you provided me/us with your entire "etterna/Themes" folder (I'm interested since I think chordjacks being labeled wrong is probably a theme-specific problem, which is incredibly weird)
Best of luck, Nick12.

**Comment by Nickito12** [comment]
@Zoqos Hello!
Because of inactivity, if there are no more responses in this issue within 1-3 weeks i will probably close it.
Have a good day!
