### ISSUE TITLE
[Bug]: Game crashes after a song if a judge other than j4 and j5 is chosen

### ISSUE THREAD

**Issue by TeamSoldierNub2** [etternagame/etterna#1194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Vague#2394, @LocalDumbahss on twitter

### Version Info

Compiled from develop

### What operating system are you seeing the problem on?

Linux (any distro)

### Bug Behavior

When you complete a song, while having a judge other than j5 or j4 chosen, it crashes after you complete the song.

### Expected Behavior

It goes to the results screen and shows the score, which you can dial back from j# to j# with - or +.

### Reproduction Steps

1.) Go into your player config
2.) Change your judge from j5 or j4 to anything else (j1 - j3, j6 - Justice)
2.5.) Go into a song (if you went into player config from the menu on the left in Til' Death, or used Rebirth's playerconfig. otherwise still go into the song and hit enter twice, then see 2. after, see 3.)
3.) Complete a song fully

### Anything else?

[Here's a video of testing with every judge except j1 and j2](https://streamable.com/l0nq3n)

**Comment by poco0317** [comment]
this issue post is kind of like opening up a box that says warning dont open or glitter goes everywhere and you opened it anyways

but ill leave it opened because it reminds me that i still havent finished these wip changes. ive rewritten the way replays save and load, and missed a couple of really specific things and pretty much only got it to the point where the game will still run under very specific conditions which i play under

**Comment by poco0317** [comment]
this was a shortlived bug that no longer is able to happen since the code has been removed and replaced
