### ISSUE TITLE
[Feature Request]: Make fakes semi-transparent by default across noteskins

### ISSUE THREAD

**Issue by Samctuary** [etternagame/etterna#1214]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

Fake notes would be slightly transparent by default in noteskins, it would use a noteskin's normal arrows, but just make them slightly transparent to differentiate them

### How Does The Feature Add To The Game?

Fakes have always been identical to normal normal notes, this has lead to them slowly being faded out of peoples consciousness by design due to how limiting that was. If they were faded by 25% opacity, or something similar, that would open the gate for many things - letting fakes become another form of expression for charters, and another gimmick style for people to enjoy. It also lets people do more creative things with charting, and let players enjoy more creative charts.

It's not identical, but a similar thing has been done by user Foxfire667 in their noteskin, where he made fakes a semi transparent outline, and it proved to open the gate for creativity. Here's a screenshot of his noteskin:
![image](https://user-images.githubusercontent.com/120126715/206526230-0f90df48-fe90-4d34-8e5d-8bb151c3386e.png)
and here's a video if the idea being used in a chart:
[https://youtu.be/w2mJa9ANBC4](url)

**Comment by poco0317** [comment]
added this as an option for all note types instead of just fakes. any noteskin can easily control the opacity of all notetypes freely. a default value for fakes has been added to each preinstalled noteskin, and in the event the values for each notetype are missing, the fallback will be 1 for all except fakes, which are set to 25%
to modify fake opacity in your own noteskin for example, add `TapFakeNoteOpacityMultiplier=1.0` to your noteskin's metrics.ini. 1.0 will cause the note to be fully visible, and 0 will bring it down to completely invisible.

to use this option for the other notetypes, follow the pattern for notetypes...
`TapNoteNoteOpacityMultiplier=1.0` ... `HoldBodyNoteOpacityMultiplier=1.0` ... etc

e4def5fa4075f4d9138cf449fcb5c6f2cdc421cc
38cf1c8d403952540567364a9faa37ddcfef605b
