### ISSUE TITLE
[Feature Request]: UI Improvements please

### ISSUE THREAD

**Issue by SkylerDaKat** [etternagame/etterna#1279]
### Is there an existing issue for the feature?

- [X] I have searched the existing feature requests

### Describe the Feature

I have a question: Have you played Osu? or almost any rhythm game?
I started playing etterna yesterday and I wanna say that I suck, I suck alot.
and I would like the following changes made to the UI:
- Add information to song labels, most importantly, difficulty and BPM
- Scroll by grabbing and flicking, you have no idea how many times I've clicked a song by accident 
- be able to sort songs (easiest - hardest, newest to oldest, you know the drill) 

I feel like these things could be useful to the game, since the game already pisses me the hell out since I find it hard to read.
like look, 
![68747470733a2f2f6f73752e7070792e73682f77696b692f696d616765732f436c69656e742f496e746572666163652f696d672f736f6e672d73656c656374696f6e2e6a7067](https://github.com/etternagame/etterna/assets/118449623/24f56dcb-4149-407d-9171-80b14dc85c1f)

You see the star rating? I wish the interface of etterna was similar to that.

I was going to make a complaint on how etterna doesnt display song pack difficulties average correctly but I came across two things:
1. In Etterna, the number of this playlist (https://etternaonline.com/pack/17744) is a 1.xx lower than the difficulty on the website
2. the difficulty switcher is almost unnoticable 

I want to remind you that I'm a new and blind player, I have never saw anyone play through this game, ever.
I saw like one clip, which is how I found out, but I had no proper introduction to the default layout (if it's even possible to change, which I'll look after I post this)

That is all for now, I'll update the post if I find anymore issues with Etterna.

### How Does The Feature Add To The Game?

this can helpful to people, like me, that are new at Etterna and have no knowledge of working around the quirks of the UI

**Comment by poco0317** [comment]
we dont usually get people telling us to add features to the ui. usually they just call it garbage. i dont intend to spend more time copying osu a second (third) time. ive also never opened osu and neither have almost all the devs. we intend to keep it that way.

however, small additions to the existing ui can be made. it would be useful for us if you made new github issues for each individual missing thing, because it is hard to track multiple things in one issue.
- the bpm and difficulty missing from song labels is nonsense. all this information is on the screen for you right next to the song name in rebirth (the default ui) and on the left side in til death. in the below images, the lone xx.xx number in the red box is the primary "overall" difficulty of the file which you should pay attention to the most. the other red box numbers are the skillsets that make it up. it is important for you to ignore the numbers which show up in the places i have surrounded with a yellow box. these numbers are set by the author of the charts and can be completely garbage.
![image](https://github.com/etternagame/etterna/assets/2531164/dd3f0a89-6861-4af4-b591-00eec265c4fb)
![image](https://github.com/etternagame/etterna/assets/2531164/c3129138-7f19-45ba-b2c2-f39cb9c4e423)


- scroll by left click flinging the wheel is a new thing nobody has asked for. it is doable, probably. we have some weird interactions with the mouse and game screen that need to be resolved. make a separate issue.

- sorting songs is built into the game in like 10 different ways. try to start by pressing up-down-up-down. i realize in the default ui there is no button visible for it. this was a minor oversight and i honestly cannot find a good spot for it
![image](https://github.com/etternagame/etterna/assets/2531164/1281144d-8973-440c-8bea-f08d85cadcf2)

- there is no plan for us to change the difficulty display to something more visual. the current system provides something a lot more specific and accurate vs star rating on a scale from basically 0-37ish. i wont elaborate further for now. see first point

- the difficulty list is shown in the first two pictures i show above in the yellow boxes. you click the buttons or you press up-up or down-down to switch.

- i dont really understand your concern about the playlist number or something. i can tell you that the difficulty numbers that appear on the website are sourced from something that is different from the game. in fact the game is separate from the website in a lot of ways so that the game can be played completely offline. assume that the number provided by the latest game version is more accurate at all times.

**Comment by SkylerDaKat** [comment]
> we dont usually get people telling us to add features to the ui. usually they just call it garbage. i dont intend to spend more time copying osu a second (third) time. ive also never opened osu and neither have almost all the devs. we intend to keep it that way.
> 
> however, small additions to the existing ui can be made. it would be useful for us if you made new github issues for each individual missing thing, because it is hard to track multiple things in one issue.
> 
>     * the bpm and difficulty missing from song labels is nonsense. all this information is on the screen for you right next to the song name in rebirth (the default ui) and on the left side in til death. in the below images, the lone xx.xx number in the red box is the primary "overall" difficulty of the file which you should pay attention to the most. the other red box numbers are the skillsets that make it up. it is important for you to ignore the numbers which show up in the places i have surrounded with a yellow box. these numbers are set by the author of the charts and can be completely garbage.
>       ![image](https://user-images.githubusercontent.com/2531164/268480670-dd3f0a89-6861-4af4-b591-00eec265c4fb.png)
>       ![image](https://user-images.githubusercontent.com/2531164/268480781-c3129138-7f19-45ba-b2c2-f39cb9c4e423.png)
> 
>     * scroll by left click flinging the wheel is a new thing nobody has asked for. it is doable, probably. we have some weird interactions with the mouse and game screen that need to be resolved. make a separate issue.
> 
>     * sorting songs is built into the game in like 10 different ways. try to start by pressing up-down-up-down. i realize in the default ui there is no button visible for it. this was a minor oversight and i honestly cannot find a good spot for it
>       ![image](https://user-images.githubusercontent.com/2531164/268480543-1281144d-8973-440c-8bea-f08d85cadcf2.png)
> 
>     * there is no plan for us to change the difficulty display to something more visual. the current system provides something a lot more specific and accurate vs star rating on a scale from basically 0-37ish. i wont elaborate further for now. see first point
> 
>     * the difficulty list is shown in the first two pictures i show above in the yellow boxes. you click the buttons or you press up-up or down-down to switch.
> 
>     * i dont really understand your concern about the playlist number or something. i can tell you that the difficulty numbers that appear on the website are sourced from something that is different from the game. in fact the game is separate from the website in a lot of ways so that the game can be played completely offline. assume that the number provided by the latest game version is more accurate at all times.

aaa I apologize qwp I can tell this isn't the first time people have complained about the UI, either.
Thanks for clarifying everything, I'll make a ticket for each issue that you've mentioned I should, 
thanks for listening to my concerns
