### ISSUE TITLE
In game IRC?

### ISSUE THREAD

**Issue by DDMythical** [etternagame/etterna#128]
With all of the etternaonline integration coming in upstream clients such as .58: Would we be able to get an IRC client in-game? I feel like this wouldn't take much to implement and would be a quite neat addition to the client.

I guess this would require people to log-on through etternaonline and link their accounts or something but I feel like this would be a really neat addition overall.

**Comment by jamesguessis** [comment]
Do it, I think it'd be easy to setup tbh. You can use any nickname you want on irc, though, so I think it'd be best to use some form of authentication with EO. Possibly only connect to it when logged in? We could even make a channel in the discord server and have a sort of bridge via EtternaBot.

**Comment by DDMythical** [comment]
"[6:42 PM] DD: i dont think its dickriding osu so much as its just something fun to have
[6:42 PM] DD: while playing
[6:42 PM] DD: or while not playing
[6:42 PM] DD: osu is a good example of a social community that has built up through ingame chats like that
[6:42 PM] DD: and i feel like integrating something like that into etterna (would it not also be possible to integrate it through discord) would just be neat and add to a social experience
[6:43 PM] DD: having it completely optional is important since not everyone wants to speak while playing and stuff"

**Comment by TheKamilia** [comment]
I dont think there is gonna be a IRC update, there a way higher chance of some Discord chat intagration

**Comment by Evanescewow** [comment]
It may seem like just sucking osu's dick but I think a full EO integration would be cool. the reason osu has those features like in game chat, friends lists and on the fly rank updating is because they're actually good features. It will be a lot to do but I think something like that would set apart Etterna as a more standalone client than stepmania and I personally think that would be awesome.

**Comment by Nickito12** [comment]
"sucking osu's dick" Not really, it is my understanding there are other, similar games with these things (And theyre nothing unthinkable/original/revolutionary afaik)
"full EO integration" There are two things i dont like about this. One is "full integration" not being clear, and the other is the mention of EO (Id like to keep things as generic as possible and give the user freedom, for example picking a server)
"the reason osu has those features like in game chat, friends lists and on the fly rank updating is because they're actually good features" I honestly dont see much point in this sentence? Dont all competitive games have these? Sounds like something that doesnt need clarification.
"It will be a lot to do" Apparently youre not aware, but EO integration has been in the works for months (And there have been experimental releases with some things). Right now things like automatic score uploads, ingame leaderboards per chart, ingame EO profiles (ratings, ranks, top scores), ingame pack downloads are all functional in the last commit (Though theyre not stable and still being tested/polished). 
"Etterna as a more standalone client than stepmania " If anything, wouldnt it be less standalone (In the case its enforced or EO Is hardcoded)?
Keep in mind this issue is meant for discussion regarding the possibility of ingame irc chat, please do not go off-topic. Most of the features i mentioned above use a rest api, and implementing chat or multiplayer with it would probably be a bad idea. Thats why irc is an option for chat. Another would be replacing the current multiplayer netcode from scratch (Maybe with something like grpc)

**Comment by jamesguessis** [comment]
let's chat with websockets :^)

**Comment by nico-abram** [comment]
Closing this since in the end we decided to make chat work through the new websockets multiplayer server
