### ISSUE TITLE
[Build Issue]: OpenSSL 1.1 has reached its end of life and is unsupported on some distros

### ISSUE THREAD

**Issue by pluiedev** [etternagame/etterna#1326]
### Have you read through the build instructions before reading this?

- [X] I have read the build instructions

### What operating system are you seeing the problem on?

Linux (any distro)

### Describe the build issue

See https://openssl-corporation.org/post/2023-09-11-eol-111/. This specifically affects NixOS/Nixpkgs where Etterna will refuse to build by default since OpenSSL 1.1 is regarded as an unsupported, broken dependency.

**Comment by WilliamImm** [comment]
Please make this a higher priority. I'm helping a friend who is trying to get this to run on [Bazzite](https://bazzite.gg/), and since its base operating system Fedora has [depreciated OpenSSL 1.1 as an option in version 40](https://discussion.fedoraproject.org/t/f40-change-proposal-removing-openssl-1-1-package-system-wide/92899), this is a hurdle for my friend.

**Comment by bluebandit21** [comment]
See: https://github.com/etternagame/etterna/issues/1215

@WilliamImm even if Fedora doesn't let you install openssl 1.1 through it's package manager, you should still be able to manually install it from its latest release within https://openssl-library.org/source/old/1.1.1/index.html
Just make sure you appropriately set `LD_LIBRARY_PATH` and co to wherever you install it to :)

**Comment by WilliamImm** [comment]
> @WilliamImm even if Fedora doesn't let you install openssl 1.1 through it's package manager, you should still be able to manually install it from its latest release within https://openssl-library.org/source/old/1.1.1/index.html Just make sure you appropriately set `LD_LIBRARY_PATH` and co to wherever you install it to :)

Already worked it out. Bazzite uses a different method of installing external deps, installing the Fedora 39 package for OpenSSL1.1 via `rpm-ostree` got it working.

However, this should still be nipped in the bud whenever possible, since as time goes on this is more and more likely gonna be an issue that makes Etterna harder and harder to run and build.

**Comment by bluebandit21** [comment]
It's been on our radar for a while now, as per that issue I linked you to :)

Have no fear, we're going to work on this, I was just trying to give you an easy workaround in the meantime.

**Comment by poco0317** [comment]
superceded by https://github.com/etternagame/etterna/issues/1330
