### ISSUE TITLE
Game crash on song wheel

### ISSUE THREAD

**Issue by Simply420** [etternagame/etterna#146]
The game crashes immediately upon pressing the "up" arrow, as if you were trying to change gameplay settings.

**Comment by Simply420** [comment]
[crashinfo.txt](https://github.com/etternagame/etterna/files/1726143/crashinfo.txt)

**Comment by Nickito12** [comment]
Looks to me like an error in the theme youre using (spawncamping-wallhack-master according to logs, though which scwh exactly i cant tell).
I recommend you make sure youre on the last version of it (Last i tried master branch on https://github.com/ca25nada/spawncamping-wallhack it worked fine on Etterna. Also afaik scwh on etterna is a WIP atm, and its possible the current master branch requires you to get the last commit in the experimental/development branch in this repo to work properly). If you provided more information (OS, etterna version/build (.58/.57 doesnt mean much) and I guess the version or build and theme youre using) I might be able to help you more.
It seems very likely youre trying to use an SM 5.2 theme in Etterna which is based on pre-5.2 (I say this because the error is "Crash reason: ScreenManager::AddNewScreenToTop: Failed to load screen ScreenNestyPlayerOptions" and theres even a warning "01:44.900: WARNING: Screen "ScreenNestyPlayerOptions" has an invalid class "".". Iirc NestyOptions is a new SM 5.2 thing. Looking into handling using unexistant screen classes without a crash might be worth looking into (But is probably also the vanilla SM behaviour).
For the time being Ill flag this as low priority since the real issue is probably handling a theme using non existant screen classes without crashnig, which, while reasonable, is in no way a priority considering a theme shouldnt do that in the first place.

**Comment by Simply420** [comment]
I see. I'll try messing around with different skins when I get home. Although are you even able to change the gameplay settings by pressing "up" on the song wheel in Etterna? I seem to remember it doing nothing at all when using the default "Til-Death" theme. Thanks for your response btw.

**Comment by Nickito12** [comment]
Iirc in both Etterna and vanilla SM options are typically shown after pressing enter again after starting a song/chart. The up arrow key shows options only during net/multiplayer play afaik (And iirc I've used it while online with til death).
