### ISSUE TITLE
Crash on selecting song from search results

### ISSUE THREAD

**Issue by GaryLeutheuser** [etternagame/etterna#169]
Etterna version: 0.56.2

Searched for "ashes", on clicking (with mouse) the song "out of the ashes" to play it, screen went black as usual, then crash occurred. Out of the ashes was the only song listed.

Log and crash info are attached (a window popped up with buttons to view them as well as an option to restart the game).

[crashinfo.txt](https://github.com/etternagame/etterna/files/2109355/crashinfo.txt)
[log.txt](https://github.com/etternagame/etterna/files/2109356/log.txt)

**Comment by nico-abram** [comment]
Thanks for the report!

Was the simfile the one from the pack "Community Keyboard Megapack - Volume 3", or "SS 3rd Style", or "Astronomic Metal Collection" (Or some other pack)?

Is the crash consistent/reproducible on your end?

**Comment by GaryLeutheuser** [comment]
The simfile is from "Community Keyboard Megapack - Volume 3".

Unfortunately, it isn't. I don't remember any more details about what I did leading up to the crash, and simply performing what I mentioned just worked totally fine several times.

**Comment by GaryLeutheuser** [comment]
I believe I may have experienced this a second time - I'm not sure what I did last time, but this time I clicked the search text to start searching, typed in "guillame" (or something close to that) and hit enter, then clicked Guillame Tell. I've attached the log and crash info from the new occurrence.

[crashinfo.txt](https://github.com/etternagame/etterna/files/2194715/crashinfo.txt)
[log.txt](https://github.com/etternagame/etterna/files/2194716/log.txt)

**Comment by MinaciousGrace** [comment]
the crashes are due to an internal fail condition that prevents you from starting gameplay after gameplay has already been started, or basically "selecting" the song twice

i'm not sure:
a) how you're triggering this beyond the safeguards already in place, it's possible you clicked at the exact same time as also hitting enter to make the selection but i haven't been able to reproduce this
b) why this fail exception exists in the first place? it seems awfully extreme for a case that i assume can be handled gracefully

my guess is if you're on an hdd and you don't have a particularly good rig it's possible that you can slip by and hit the redundancy check, either that or you're managing to hold tab (slowing down the game) which has been a factor in other difficult to reproduce bugs

my guess is whatever issue the fail exception was meant to avoid is no longer relevant and it can be safely removed or replaced

**Comment by MinaciousGrace** [comment]
hopefully solved with no added sideeffects by 10da38e3fb673055a90e04beb34109c27ca33b61
