### ISSUE TITLE
Customize Gameplay is asymmetrical

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [etternagame/etterna#187]
Downscroll: ![Reversed](https://cdn.discordapp.com/attachments/261811430888570880/443635885309689857/unknown.png)

Upscroll: ![Unreversed](https://cdn.discordapp.com/attachments/261811430888570880/443635819433951233/unknown.png)

I would expect the receptors to symmetrically be positioned at the edge of the notefield.

**Comment by nico-abram** [comment]
I agree. The only problem is we might need to add some offset for one option. Meaning when people who already have offsets for that option (Say, downscroll since afaik its the least used, however its stilll used quite a bit) download the next version their receptors will be in the wrong place. This could probably be fixed with some stored flag to check if its an old offset, and checking it to add some correction of the old offset to the "new coordinates" or w.e.
I think the relevant lua is here https://github.com/etternagame/etterna/blob/develop/Themes/Til%20Death/BGAnimations/ScreenGameplay%20overlay/WifeJudgmentSpotting.lua#L685

It would probably be symetrical if we first check if its downscroll or upscroll, and then either addy(offsety) or addy(-offsety).

**Comment by nico-abram** [comment]
In order to check if its downscroll we can probably use:
```lua
GAMESTATE:GetPlayerState(PLAYER_1):GetCurrentPlayerOptions():UsingReverse()```
from lua
