### ISSUE TITLE
Autosync Deletes .sm Files

### ISSUE THREAD

**Issue by flodinl** [etternagame/etterna#290]
When you press F6 during the song to autosync, then choose to save the new offset, the .sm/.dwi files for the chart are deleted. This causes the game to crash when you try to play the file (and renders autosync useless). It appears that the old .sm is preserved in the folder but renamed ".sm.old," so maybe something bad is happening internally in between renaming the old file to .old and writing the new one?

**To Reproduce**
1. Select a song
2. Press F6 during play to autosync
3. Play enough of the file for the offset to adjust
4. Hold Esc to exit gameplay
5. At the prompt, select that you want to save the new offset

**Expected behavior**
A new .sm file should be created with the new offset resulting from the autosync.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.60

**Comment by poco0317** [comment]
I can't reproduce this exact issue. What happens is that the .sm (or whatever it is) gets renamed to .sm.old. It is not deleted. This is intended, to preserve the original offset.
A new file is created, which should be a .ssc file. The game should force a reload from disk at this point to load that instead of the old .sm.
For the record, using autosync again on the newly generated .ssc file does the same procedure which leaves me with an additional .old file. Still intended, but odd.
I do not crash when I try to play the file again before and after restarting the game. Check your log.txt in the /logs/ folder of the game install after closing/crashing the game. It may output a little info regarding whether or not the saving of the new offset file failed.

Is there a specific file you have this problem with? If it is every file, you may be having a permissions related issue, if you are installed in a directory like "Program Files."

**Comment by flodinl** [comment]
Yeah, it was a permissions issue. My Etterna folder was some how set to Read-Only, so saving the autosync was renaming the .sm to .sm.old but then failing to write the .ssc. It might be helpful to display an error when this happens since I think it isn't obvious what's going on without investigating.
