### ISSUE TITLE
Percentuntilcolorcombo not able to display color after finishing a song

### ISSUE THREAD

**Issue by Sklitterbeer** [etternagame/etterna#342]
**Describe the bug**
The variable percentuntilcolorcombo=x in Etterna's fallback seems to not be able to display a color, in this case green, yellow or light blue, at the end of a song instead of a quarter in. When the variable is changed to 1, 0.99. 0.95 0.90 or 0.75, the color never displays.

**To Reproduce**
1. Go into Etterna's fallback theme
2. Change percentuntilcolorcombo in metrics.ini to 1, 0.99 or 0.95
3. Play a song, no matter what length
4. When finished, color will not display.

**Expected behavior**
That, when the song were finished, it display a color on the combo counter representing the grade one had achieved.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
Using F2 and restarts have been attempted. It seems that the program can't display any other combo color variable except 0.25, but this needs to be tested.

**Comment by MinaciousGrace** [comment]
percentuntilcolorcombo functions  as expected fine for me using 0.75 0.86 0.95 on multiple test songs, it was probably not working for you given the other similar issues you had due to an installation error

there is an actual concern over 100% color because the way the internals are setup the comparison is song position vs song length and the precision is i guess not good enough to reliably ensure activating the color combo on the very last note

it can probably be done but it would involve overhead and if you want some sort of full combo celebration stuff it's faster/more flexible to do it in the lua combo scripts directly

some psuedo code for reference

if (combo == totalnotes) self:diffuse(fullcombocolor)
