### ISSUE TITLE
Enhancement/FR: Current Session Plays/Stage

### ISSUE THREAD

**Issue by SpoOkyMagician** [etternagame/etterna#360]
I was looking though the different stats and such and The closest thing I see is "Plays". However, this is the total. Not the current session. Could this be added in the string? For example...

77 Plays (5 Plays this session)

Something along those lines. Would be nice.

**Comment by poco0317** [comment]
At the moment this number can be obtained in Lua through ```STATSMAN:GetPlayedStages()```
Simply making this addition proves to be buggy, because the number also increments when you view Replays or fake Eval Screens. This is due to the way we reconstruct the playerstagestats when doing that. For this to be fully finished, we would just have to handle that a little better.

**Comment by MinaciousGrace** [comment]
subsumed in https://github.com/etternagame/etterna/issues/482
