### ISSUE TITLE
Misc Bugs here and there.

### ISSUE THREAD

**Issue by SpoOkyMagician** [etternagame/etterna#364]
I made a theme that uses etterna's fallback theme. I went though trying to debug a few things here and there. I found a few issues.

(Missing Metrics)

ScreenSelectPlayMode::ChoiceNonstop=""
ScreenSelectPlayMode::ChoiceOni=""
ScreenSelectPlayMode::ChoiceEndless=""
OptionExplanations::FullTapExplosions="" <s>(I could not actually get this one to work. Must be broken.)</s>

(Menu Options)

Jukebox does not work. Should be removed.
Edit Step/Chart does not work. Should be removed.

(Crash)

Couples Mode crashes the game. Needs to be removed.

(Concerns)

Verses <s>and Doubles</s> work but should be removed. (Since player 2 was removed, likely, this will not work in <s>doubles/</s>verses.)
Nonstop, Oni, and Endless should be removed. (If done, you can ignore the metrics then.)

-----------------------------------------------------------------------------------------------------------

More bugs found. The following seemed to have been removed from the game:

(However, I did a search in the repo and some things still remain noting these, Please be sure to remove them if this is the intended case.)

SONGMAN:GetNumCourses();

Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/other.lua
src/SongManager.cpp
Docs/Luadoc/Lua.xml
Docs/Luadoc/LuaDocumentation.xml

SONGMAN:GetNumAdditionalCourses();

Docs/Luadoc/LuaDocumentation.xml

SONGMAN:GetNumLockedSongs();

Docs/Changelog_sm5.txt
Docs/Luadoc/LuaDocumentation.xml

Update: SONGMAN:GetNumCourses(); seems to work. Although, it should be removed anyway.

Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/other.lua
src/SongManager.cpp
Docs/Luadoc/Lua.xml
Docs/Luadoc/LuaDocumentation.xml

Update: Hmm... Seems GAMESTATE:GetCurrentStage(); was removed as well? Oh well.

Docs/Changelog_sm5.txt
Docs/Luadoc/LuaDocumentation.xml

Update: I am unsure but, I think this is removed. PREFSMAN:GetPreference("PercentageScoring"); Although, a few references to it.

Themes/_fallback/Languages/zh.ini
Themes/_fallback/Languages/es.ini
Themes/_fallback/Languages/fr.ini
Themes/_fallback/Languages/ja.ini
Themes/_fallback/Languages/nl.ini
Themes/_fallback/Languages/pl.ini
Themes/_fallback/Languages/de.ini
Themes/_fallback/Languages/en.ini
Docs/old_changelog.txt
Docs/Changelog_sm-ssc.txt
Themes/_fallback/metrics.ini

Update: Unsure of this but likely my theme. Check into metric ComboContinuesBetweenSongs.

Update: Two others found. Unsure still. DancePointsForOni <s>and MenuTimer</s>.

**Comment by nico-abram** [comment]
I think doubles should maybe stay (Since afaik its basically 8k)

**Comment by SpoOkyMagician** [comment]
Fair enough.

**Comment by MinaciousGrace** [comment]
there's probably a lot more of these especially in metrics, especially with recent changes
it would be nice if we had a programmatic way of cleaning out extraneous stuff 

since you're already compiling a list of stuff i'll note metrics for things that i just removed

selectmusic internal cdtitle/banner actors

**Comment by SpoOkyMagician** [comment]
Fair enough about docs. Although, I will leave it for now since it needs to be done eventually.

**Comment by poco0317** [comment]
Metrics:
- Moved the FullTapExplosions explanation from Til Death to fallback
- Removed fallback references to oni/endless/rave in that specific scenario
- Removed fallback title menu choice references to jukebox
- Redid fallback title menu reference to ingame editor (it should be a hyperlink)
- Removed the bad fallback reference to ComboContinuesBetweenSongs (we should probably remove the arcade options screen)
- Removed bad fallback references to missing UI options DancePointsForOni, MenuTimer, ShowBanners. While the MenuTimer still exists in the code, we would like to remove it.

Other:
- Removed some misc preferences and fixed (badly) the edit profile softlock

Will consider removing oni/endless/rave soon because it holds a lot of random vars in the c++ as well that don't really do anything.
45da444686a93a43589bac211c8b0b62e8c2995b
180feaaea25e3efbfcd77aec7dafd767ede77345
2337ca063bcc10eee7ebd49b5bc36054c623ed42

**Comment by poco0317** [comment]
I believe all of the mentioned things in this have been removed or taken care of as of 0.65.1.
