### ISSUE TITLE
[Feature Request] Individual Online Scoring MSD Results Displayed In-Game

### ISSUE THREAD

**Issue by anani88** [etternagame/etterna#365]
Feature Description:
Leader-board results for specific skill-sets shown on the results screen in-game.

The MSD of a file in-game has the following skill-set ratings
Overall: 19.98
Stream: 15.67
Jumpstream:14.07
Handstream:11.21
Stamina:17.59
Jackspeed:19.98
Chordjack:13.78
Technical: 18.73

After playing the sim-file the scoring results should show me that I scored

Overall:15.98
Jumpstream:15.67
Handstream:12.21
Stamina:15.59
Jackspeed:17.98
Chordjack:11.78
Technical: 17.73

When on the music wheel and pressing hotkey 3 (or clicking Scores) it displays what my personal MSD rating was for that chart. In this example. I need to practice more.

Here is a picture example for a better reference: http://i68.tinypic.com/ek5k3l.png

**Comment by nico-abram** [comment]
I am not entirely sure what this request is about. Do you want to see all skillsets in the leaderboard in scores tab (3) in the online part?

**Comment by anani88** [comment]
> 
> 
> I am not entirely sure what this request is about. Do you want to see all skillsets in the leaderboard in scores tab (3) in the online part?

Hi Nico-abram,
Yes, that's exactly what I would like to see. I'd like to see what my skill-set's were rated as for the song that I played in the Scores window on the music select screen/wheel. 

It would be nice to be able to see where I'm at with my skill-sets visually with a MSD comparison side-by-side when playing Online. Just getting a letter grade score and a percent with no other information as a general idea of where my skill-sets are at is too vague.  If I scored a B, 77% <-- that doesn't tell me anything other than I really need to practice more, but practice what? Chordjack, Jackspeed, Stream etc. 

Do you see what I mean?

**Comment by nico-abram** [comment]
```
It would be nice to be able to see where I'm at with my skill-sets visually with a MSD comparison side-by-side when playing Online
```
comparison to what?

Maybe some drawing could help get the idea accross

**Comment by MinaciousGrace** [comment]
the tab originally had the full information, but they were removed due to clutter on the screen and because those numbers just tell you how much that particular score/file contributes to your rating in each category

they don't tell you what you should improve in order to score better on that file, or more broadly what you should aim to improve in general

i agree it would be useful to display the skillset classification being referred to, and i could theoretically add a mouseover to display all of them, but again the worry is that information may be interpreted to have more meaning than it does

**Comment by MinaciousGrace** [comment]
added 1dab3619c56a5a925738562483d2d8873951bdeb
