### ISSUE TITLE
Move to lua musicwheel

### ISSUE THREAD

**Issue by MinaciousGrace** [etternagame/etterna#376]

**Comment by nico-abram** [comment]
There's a prototype implentation here: https://github.com/etternagame/etterna/blob/13267c3a4bfcf1c0713b77496ff1a4361e1ce4ed/Themes/Til%20Death/Scripts/11%20Wheel.lua

As of right now, it has no steps/difficulty selection stuff (Should that be a separate thing?), but it should be able to display packs, open/close them and move around. In order to replace the c++ one some stuff to 1) disable it and 2) set the "current song" in c++ from lua should be added.

**Comment by nico-abram** [comment]
Since rebirth uses a lua music wheel, I'm gonna close this for now
