### ISSUE TITLE
Remove useless/legacy sorting

### ISSUE THREAD

**Issue by PPProviden** [etternagame/etterna#394]
Player's Best! Sorting returns an -EMPTY- folder with nothing inside.
![2018-12-01_160247](https://user-images.githubusercontent.com/31165158/49325785-f765d600-f582-11e8-9493-db48f8ce4aa1.png)

Preferred Sorting returns the entire songlist.

Recent Sorting returns all songs with titles starting with a number and nothing else.

They serves no practical purpose and should be considered removable.

**Comment by nico-abram** [comment]
I think eventually we plan to "deprecate" or w.e the C++ music wheel and put a somewhat generic and simple lua music wheel in _fallback Scripts (And obv. use it in Til Death). Imo grouping/song sorting/group sorting options should also go in the filters tab

**Comment by nico-abram** [comment]
Removing a sort from the current C++ wheel should be relatively simple:
Remove the enum case from these 2 switches: https://github.com/etternagame/etterna/blob/07270e6a76cf63f88420ec0ef0e2d007205cc20f/src/SongUtil.cpp#L672 and https://github.com/etternagame/etterna/blob/13267c3a4bfcf1c0713b77496ff1a4361e1ce4ed/src/MusicWheel.cpp#L751
And then the enum definition in https://github.com/etternagame/etterna/blob/07270e6a76cf63f88420ec0ef0e2d007205cc20f/src/GameConstantsAndTypes.h#L182 .
Finally, remove the entry for the tostring map in https://github.com/etternagame/etterna/blob/07270e6a76cf63f88420ec0ef0e2d007205cc20f/src/GameConstantsAndTypes.cpp#L129

**Comment by hitonisan** [comment]
To update this based on my observations in Etterna 0.66.1:
-"Player's best", which still leads to the "Popular" sort as shown above, still doesn't do what it would imply. It only shows the first 30 songs on the machine that come alphabetically, and nothing else:

![Player's Best Sort Example](https://user-images.githubusercontent.com/37351790/69664486-1724c280-104e-11ea-9a54-9e22edcde076.png)

-"Recent", AKA "Recently Played", also doesn't function the way you'd expect it to, as it produces the same results as "Player's Best":

![Recent Sort Example](https://user-images.githubusercontent.com/37351790/69664572-420f1680-104e-11ea-97a3-74966799d805.png)

-"Preferred" remains as described above, providing the entire songlist in alphabetical order without groups. I personally see this sort as redundant, though, since the "Title" sort already exists.

**Comment by richardjharris** [comment]
The Preferred sort is useful when using filters, as it disables grouping by song pack. Personally I rarely care what pack a song is from, especially when filtering by tag or difficulty. So if we remove those sorts, it would be useful to have some other way to enable/disable pack grouping, perhaps orthogonal to the sorting and filtering code.

**Comment by MinaciousGrace** [comment]
set musicwheelusessections = never in preferences.ini to never group things

preferred sort, recent sort, and popular sort have been removed

recent sort will probably just be replaced by a last 250 scores obtained tab in profile, or something
