### ISSUE TITLE
Make taking screenshots easier and more useful

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [etternagame/etterna#417]
Current PrntScr takes a screenshot with only a date in the name and also works as a regular PrntScr taking a picture of the entire screen, which is quite garbage when you're playing windowed mode and only want to post a screenshot of the game to Discord or something.

Change the naming to something more useful like chart name, rate, score, screen or date and maybe add a hotkey to copy the screenshot to clipboard, not unlike what ShareX allows you to do.

**Comment by nico-abram** [comment]
It seems, at least on windows, copying images to the clipboard is much more complicated than text. Maybe linking https://github.com/dacap/clip/ and using it directly in the base HOOKS (architecture hooks) singleton class for clipboard text/image functions might be worth it (That way we'd also get clipboard copying and clipboard copy/pasting would be cross platform instead of windows only)

This is the function that names screenshot files: https://github.com/etternagame/etterna/blob/13267c3a4bfcf1c0713b77496ff1a4361e1ce4ed/src/StepMania.cpp#L1300 (More specifically, the line that does so)
It seems the evaluation screen calls that function: https://github.com/etternagame/etterna/blob/13267c3a4bfcf1c0713b77496ff1a4361e1ce4ed/src/ScreenEvaluation.cpp#L781
In here the current song/steps(aka chart) should be accessible. We could add a last optional parameter to the SaveScreenshot function for a forced filename, generate a name and pass it. What format for files would be appropiate? Should we support multiple formattings for screenshots based on a preference?

**Comment by poco0317** [comment]
We could add a simple input screen in the options menu somewhere to allow changing the format, given a particular format string input. Like replacing {date} in the string input with the actual date or whatever.

**Comment by MinaciousGrace** [comment]
this seems redundant and burdensome
