### ISSUE TITLE
Preview notes Desync with audio

### ISSUE THREAD

**Issue by BrokenGale** [etternagame/etterna#444]
**Describe the bug**
Notes in preview de-syncs against the audio

**To Reproduce**
1. Open Etterna 0.64.0
2. Highlight a song
3. Click Preview Chart
4. See the de-sync.

**Expected behavior**
The preview synchronizes with the song to produce an accurate representation of auto-playing the chart

**Desktop (please complete the following information):**
 - OS: Windows 7 (Reproducible on other OSes)
 - Version: 0.64.0

**Comment by poco0317** [comment]
This issue is actually specific to certain songs and not every single one. Can you give particularly notable examples? I believe World Sound is one.

**Comment by Void345** [comment]
isnt this mostly fixed in 0.65

**Comment by poco0317** [comment]
No, and some people claim it is worse.

**Comment by Void345** [comment]
huh, everything ive looked at on 65 has been fine

**Comment by MinaciousGrace** [comment]
global offset isnt accounted for by the preview so the greater it is the more offsync it looks

**Comment by MinaciousGrace** [comment]
i've tagged this for hotfix tentatively because i think some of the desync can be fixed by properly accounting for global offset, however i'm not entirely sure how difficult that will be and i'm not entirely sure there aren't multiple sources of desync

i.e. this may get fixed, probably will get fixed a little, or may not get fixed at all

**Comment by MinaciousGrace** [comment]
4fc06ba4cd8de84e5b9e39ce8d7df80e4c096f7e mostly but not completely fixes the issue

**Comment by poco0317** [comment]
Some ideas have been going around as for a possible way to fix this. It seems that the consensus to fix it would be to make ScreenSelectMusic hold its own music pointer rather than tell the sound manager to just play sound. The commit mentioned above was reverted after further thought into the matter.

**Comment by poco0317** [comment]
Fixed in gameplay rewrite by a combination of commits, but this one primarily: 7f6148d5a93ea181bfa8de42f6cdef3e869c992d

the issue was with vbr mp3 files
closed when merged
