### ISSUE TITLE
Exit in "NETWORK OPTIONS" leads to multiplayer

### ISSUE THREAD

**Issue by YChvanov** [etternagame/etterna#448]
**Describe the bug**
When I press exit in "NETWORK OPTIONS" the game goes to Multiplayer

**To Reproduce**
1. Go to 'Options' -> 'NETWORK OPTIONS'
2. Click on 'Exit' at the bottom
3. See multiplayers profile select menu

**Expected behavior**
I wanted to go back to the options or to the main menu

**Screenshots**
Pretty straight forward

**Desktop**
 - OS: Windows 10 LTSB 1607
 - Version: 0.65.0

**Additional context**
Nothing

**Comment by MinaciousGrace** [comment]
the exit button is redundant with the escape key functionality, iirc esc returns you to the proper menu and has correct branching

since the exit button is hardcoded into the options screens it was more difficult to do this, so i left it alone pending an overhaul of the options menus entirely, however it's probably prudent to just remove the button for the time being

**Comment by MinaciousGrace** [comment]
took the lazy way out a64486dc8201bf263b7e513211115b4284768cec
