### ISSUE TITLE
Fix multi eval viewing

### ISSUE THREAD

**Issue by nico-abram** [etternagame/etterna#462]
You can pretty much never see your own score after clicking someone elses, and sometimes some peoples dont work. Also need to increase precision on ssr in multi(It seems to get rounded. Probably when parsing/creating the json). SSR is sent here: https://github.com/etternagame/etterna/blob/develop/src/NetworkSyncManager.cpp#L1334 which looks fine. Maybe change the 0 in https://github.com/etternagame/etterna/blob/develop/src/NetworkSyncManager.cpp#L819 to 0.0? It's also possible it's getting rounded server-side

**Comment by poco0317** [comment]
For offset plot fixing:
Part of the issue lies in desynced indexing between lua and c++.
Refer to mpscoreboard.lua for visual sorting and selecting offset plots.
Refer to ScreenNetEvaluation.cpp for the original and attempted redo of setting the player for offset plots (SetCurrentPlayer(index) and SetCurrentPlayerByName(string))

**Comment by nico-abram** [comment]
I'm closing this for now. If we find out this still happens under any circumstances we can reopen it
