### ISSUE TITLE
Switching between SP and DP difficulties enables preview

### ISSUE THREAD

**Issue by YChvanov** [etternagame/etterna#465]
**Describe the bug**
When I switch from SP to DP or vice versa preview enables

**To Reproduce**
1. Find a track with both SP and DP difficulties (e.g. 'Babel' in 'Doubles Tournament Expansion R3')
2. Select DP chart using double arrow-down or by clicking on difficulty level
3. See preview appeared

**Expected behavior**
I wanted just to switch difficulties

**Screenshots**
Nah

**Desktop (please complete the following information):**
 - OS: Windows 10 LTSB 1607
 - Version: 0.65.1

**Additional context**
It wasn't like that on 0.64.0 for sure
It doesn't open preview if switch between just SP or just DP charts
This is especially annoying when you scroll through songs and there's a single DP simfile which enables preview you don't wanted

**Comment by poco0317** [comment]
I believe this behavior was actually present on 0.64. Nevertheless, it is not completely intended, but it is a side effect of some hacky business going on in the background to make sure you don't crash when you do almost anything with preview being activated since the last screen reset.
Specific to the case you are seeing, this is a result of making sure that switching styles, thus reloading your noteskin and the notefield, regenerating the preview, and resetting the music, does not deadlock your game when you have the visualizer on.

This may be fixed in .66 if we do a rewrite or cleanup of ScreenSelectMusic. There are a lot of ideas on how to fix this, but it's probably going to turn out to be a lot of work.

**Comment by poco0317** [comment]
Fixed for next release 20bc0d4d9e634d1a2e9c8f44e9a525aaf2bf4a0a
