### ISSUE TITLE
Osu beatmaps with a [Colours] section do not load

### ISSUE THREAD

**Issue by shockdude** [etternagame/etterna#486]
**Describe the bug**
Etterna does not load Osu beatmaps that contain a [Colours] section.
Manually deleting this section in each .osu file allows the beatmap to load ok.

**To Reproduce**
1. Attempt to load an Osu beatmap that contains a [Colours] section, e.g. https://osu.ppy.sh/beatmapsets/127305
2. The chart doesn't show up in-game.

**Expected behavior**
The chart loads and is playable in-game.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version 0.65.1

**Comment by MinaciousGrace** [comment]
1a31e7441fe9e53476897b22e43f2bd5eb05e560

to recap a lengthy discussion this was being caused by moving packs back and forth from a mac to a windows machine causing the mac resource forks to prevent files from loading after the change to allow ._pulse was made, so i've put back the resource fork screening but added an exception for ._pulse

**Comment by MinaciousGrace** [comment]
ed0c39396a7e0d6885462238289ba69bedafa0ff

hasn't been 100% tested but it should work
