### ISSUE TITLE
Add a keybind for skipping long intros before the chart starts

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#491]
For songs that have a long intro (such as the 54 second intro for Saw-Saw in SPEEEDCOOOORE 4) it would be great if there was a keybind to skip to ~3 seconds before the actual chart starts. Quite a few songs with long intros don't get much play since it's annoying to wait when you are repeatedly playing it.

**Comment by YChvanov** [comment]
Oh, I wanted to request this
Additionally, we shouldn't forget that there's mines-intro's in some simfiles (such as in "Yuru Fuwa Jukai Girl" by Wh1teh) which are adding a bit more challenge, so if there's a mines before notes we should teleport to them

**Comment by Kangaroux** [comment]
@YChvanov Just so I'm understanding correctly, are you saying mines should be considered the start and it should jump to them, or it should jump to the first note?

**Comment by YChvanov** [comment]
To mines meant I

**Comment by Kangaroux** [comment]
I think that should be a configurable option, because I would like to skip over mines. It's not uncommon for songs to have mines during the intro that are there simply so you have something to look at while you're waiting.

**Comment by MinaciousGrace** [comment]
there are a number of reasons i actively do not want to do this but honestly it mostly comes down to the fact that if people put idiotic intros into their files that are so bad it prevents people from playing them, then those files shouldn't be played

and maybe those people will learn a lesson instead of being coddled by backend code
