### ISSUE TITLE
In practice mode, add click and drag to highlight part of the NPS graph which will pause the song when it reaches the end of the highlighted region

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#496]
As an alternative to simply marking a return point in the hit graph, it would be great for practicing a section multiple times. The reason for pausing at the end is for #495, so you can play a section from start to finish and see what your judgement counts look like. Manually pausing by right clicking isn't perfect since you'll probably end up with a few combo breakers in doing so.

**Comment by poco0317** [comment]
Intended 0.65.0 feature not added due to time constraints.

Implementing this may involve a little bit of effort but can be done entirely in Lua I think. Just kind of have to come up with a good way to detect dragging (which I think we have done in some form for the collapsible scoreboard). After that, it's a matter of using an update loop or function to check if the song passes the end point of your loop region.

**Comment by poco0317** [comment]
Practice Mode now has a region setting in addition to a bookmark. Right clicking the graph once adds a bookmark. Right clicking a second time changes to a region mode. Right clicking more times in new locations expands the region or makes it smaller depending on the placement of the clicks. Right clicking twice in the same spot resets the region to a bookmark.
Loop regions can be jumped to the same way as bookmarks: with backspace.
Loop regions loop the music and notedata, obviously.

closed when gameplay rewrite pr merged
