### ISSUE TITLE
Some song not loading when packs are added directly to Etterna\Songs Folder

### ISSUE THREAD

**Issue by mattbox** [etternagame/etterna#515]
Hi,

I've been having issues since 0.64.0 with getting certain songs to show up in the game. It appears to be any song folder that starts with a "(".
This only happens when I add a pack to `Etterna\Songs\` if install them through the in game downloader they load fine, I think the packs themselves are being loaded since they do show up in the game if at least one song in them doesn't start with a (.
The packs also show up as downloaded in the in game downloader if the pack folder is in `Etterna\Songs\` even if none of the songs are show up in game.

**Comment by MinaciousGrace** [comment]
1a31e7441fe9e53476897b22e43f2bd5eb05e560

to recap a lengthy discussion this was being caused by moving packs back and forth from a mac to a windows machine causing the mac resource forks to prevent files from loading after the change to allow ._pulse was made, so i've put back the resource fork screening but added an exception for ._pulse
