### ISSUE TITLE
Holds borked in practice after seeking

### ISSUE THREAD

**Issue by Ulti-FD** [etternagame/etterna#583]
I've been told this was mostly fixed in .65.1 but it's not completely patched. Seeking in practice mode causes holds to do all sorts of odd things. They can show up already dropped when they haven't been played yet, they can show up as invisible until initially held, they can show up late and in the worst case they can show up early and hide the arrows that are supposed to be before it.

**To Reproduce**
-Play this file (https://cdn.discordapp.com/attachments/395382822837157898/593224400069722112/Field_Kaerezu_no_Chi_suicidaln00b.zip) at the section shown in the example in preview
-Retry the section a few times, things will get get very glitchy

**Example**
https://streamable.com/edit/ildcf

(ver .65.1, win64 build)

**Comment by poco0317** [comment]
Fixed by some random commit in gameplay rewrite pr.
Not sure what exactly since it was a combination of factors. Practice Mode now reloads all notedata every time you seek, but resets it in a way so that past/passed notes aren't loaded. If a region is selected, the notedata is truncated to the region. More info on that available in the full details when the whole thing is complete.

closed when pr merged
