### ISSUE TITLE
Crash when exiting Gameplay when downloading pack

### ISSUE THREAD

**Issue by arvinkent098** [etternagame/etterna#589]
When you're downloading song packs and started playing while the download is still in progress, the game crashes when going to result screen.

It happened twice when I PFC charts while doing those.

**Comment by poco0317** [comment]
I did not immediately reproduce this crash. Please provide the crashinfo.txt or at least the crash reason listed at the top of it.

We are looking into reproducable ways to crash the game which may be related to this type of event. The reason the crash "waits" until gameplay exit is definitely because it is related to something which runs in the background that is not allowed to update until we are not on a gameplay screen.

Other people have reported simply scrolling on the music wheel (and provided no more info than that)
Loading chart leaderboards may be related.
Using literally any online (not multiplayer) integration may be related.

**Comment by poco0317** [comment]
This crash was reproduced by chance in a debug session and the cause was found. A fix will be in the next update. It is related to online integration.

**Comment by Defluxit** [comment]
Should've specified it was after playing Game Time 0.8x in Jumpjack Resteps. Crashed 2-3 times after finishing the song. Session was maybe 2 hours after the first crash, not sure if that affects it, as in a memory leak or something.

**Comment by poco0317** [comment]
The `Stack Overflow` crash reason is very rare and typically only has 1 cause. Most current causes are due to us logging chart leaderboard request response dumps upon error. The behavior of the song ending and crashing before reaching results is consistent with this, since the online integration begins updating again once gameplay is exited.

**Comment by Defluxit** [comment]
I switched over to version 0.66.1 in hopes that it would stop crashing every once in a while, but it has started crashing after basically every file I play now. 
[crashinfo.txt](https://github.com/etternagame/etterna/files/3588496/crashinfo.txt)
[log.txt](https://github.com/etternagame/etterna/files/3588497/log.txt)

**Comment by Defluxit** [comment]
I read that it was due to online integration so that was just a waste to post lol.

**Comment by poco0317** [comment]
probably fixed in #654
