### ISSUE TITLE
Translation For Failure Types in ScreenOptionsAdvanced

### ISSUE THREAD

**Issue by SharpnelXu** [etternagame/etterna#596]
**Describe the bug**
Translations are there but are not used

**To Reproduce**
1. Go to ScreenOptionsAdvanced with non English Language
2. See Failure Types not translated

**Expected behavior**
Expect the options to be translated

**Additional context**
[Should be this function.](https://github.com/etternagame/etterna/blob/425f10cfd58473754bba9021fc6f441e1accaefc/src/Etterna/Screen/Options/ScreenOptionsMasterPrefs.cpp#L366) I don't know how to fetch translated strings in C++, and the documentation does not have a search function. Should be an easy fix tho.

**Comment by poco0317** [comment]
The fix is to partially or totally revert this commit. Change the second parameter from DefaultFailChoices back to a list of the fail type strings. I don't see why this is being done this way. It is bad to hardcode values in this spot, but the values are hardcoded anyways. The true solution here would be to make the strings translate from the function, but I feel like this would somehow introduce complication.

Tested the change and the only result is that the default fail types in advanced options properly translate and nothing else is affected. 

https://github.com/etternagame/etterna/commit/9b847caa45904ef14ab5233251e8cd83cc15a80a#diff-dfbf6a2e315ee935b79bdc4dd9a6c091L711

**Comment by poco0317** [comment]
Resolved in #597
