### ISSUE TITLE
Autosync doesn't correctly write .ssc for old files using .dwi

### ISSUE THREAD

**Issue by flodinl** [etternagame/etterna#623]
This is exactly the same bug as https://github.com/etternagame/etterna/issues/307, I think it was fixed for a while (maybe? can't quite remember), but it now happens again, 100% reproducible on any file with only a .dwi and not a .sm.

Basically when autosyncing a file like this the .dwi is renamed to .dwi.old and a blank .ssc is created with metadata but no chart data. Then when you try to play the file, the game crashes due to the blank .ssc.

Probably also the source of the crash in https://github.com/etternagame/etterna/issues/493.

**Comment by poco0317** [comment]
To speed up this process, it would be good to have a specific example file this consistently happens to. I am aware there are many dwi files that exist, but it's good to be consistent and specific.

**Comment by flodinl** [comment]
Judgment Days from PPP2 is an example of such a file.

**Comment by poco0317** [comment]
Odd. Reproduced.

**Comment by MinaciousGrace** [comment]
i distinctly remember tracking this down and reliably fixing it, not sure what we did to re-break it, as the issue was that a function was removed dealing with composite notedata (charts for doubles play that had specific notes for player 1 or 2 for which support was removed)

the function was part of the read/write process for _all_ notedata, composite or not, and removing it prevented notedata writeout if it didn't already have a source file that did not need to be converted such as an existing sm

again not sure what we could have changed to mess with this but it's hard to imagine this isn't related somehow to the resurfacing of the issue

**Comment by poco0317** [comment]
fixed by bd9448e917b4aa04521b346ded6887b70c0ce74d
