### ISSUE TITLE
CP cannot stat

### ISSUE THREAD

**Issue by toprak** [etternagame/etterna#632]
I tried to install ettern

**To Reproduce**
1) yay -S etterna-git
2) wait for finish setup and it says cp cannot stat:no such file directory

**Expected behavior**
Expected behavior is succesful setup.

**Screenshots**
https://imgur.com/a/Sh2Hc04
**Desktop (please complete the following information):**
 - Archlabs
 - XFCE4
 - 64bit 

**Additional context**
cp: cannot stat '/home/anonim/.cache/yay/etterna-git/src/etterna/etterna': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
Error making: etterna-git
.

**Comment by izik1** [comment]
So, I recently (as in, just a ~~couple~~ ~~few hours ago~~ yesterday technically) tried to install Etterna via [`etterna-git` (AUR)](https://aur.archlinux.org/packages/etterna-git/). Ran into this and asked 

This happens because at some point the executable got renamed from `etterna` to `Etterna`, additionally, after fixing that, `GtkModule.so` no longer exists, so the line related to that has to be removed from the PKGBUILD as well.

I eventually decided to make a non `-git` AUR package for [`etterna` (AUR)](https://aur.archlinux.org/packages/etterna), since it felt like that would make sense here.

**Comment by monotron** [comment]
I will update the AUR package after work, test and report back within 24 hours.

**Comment by poco0317** [comment]
There is a single report that this currently works.

**Comment by hexptr** [comment]
Pushed an update that should fix things as of v0.70.1.
