### ISSUE TITLE
Song playing while "paused" on chart preview

### ISSUE THREAD

**Issue by sebaex** [etternagame/etterna#634]
**Describe the bug**
Text _Paused_ is shown on preview while song is playing

**To Reproduce**
1. Go to any song
2. Pause it without preview
3. While paused, preview it

**Expected behavior**
The song should be playing while text _Paused_ still in the playfield

**Screenshots**
Video is more suitable https://youtu.be/LyaVwtwAtus

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1903
 - 64bit or 32bit: 64bit

**Comment by poco0317** [comment]
Very simple oversight that can be fixed in one of two ways from either Lua or C++.
An explanation of why it happens on the programming side of things is pretty much equivalent to the reproduction steps here. If you pause the preview and switch songs, another song starts and disregards the pause boolean. The pause boolean is not reset and not correctly checked either in Lua or in C++. Which one is up in the air, really. Either C++ should be pausing the music immediately, or Lua should not be displaying the "Paused" text.

**Comment by poco0317** [comment]
Duplicate #614
