### ISSUE TITLE
Dependency on proprietary blob `calc`

### ISSUE THREAD

**Issue by atoms118** [etternagame/etterna#641]
- What's the reasoning for this code being closed source?
- If it absolutely must be closed source, why is it not an optional dependency?

**Comment by poco0317** [comment]
The reasoning for it being closed source is a kind of mix of a few things.
Let me also say that it is not closed source. It's just harder to find, and we provide it in a way that isn't obvious on purpose so that people who don't know what they are doing don't mess with it.

- We don't want it to be copied without credit (I mean come on, really)
- The structure of the code is messy. Relatively unreadable by someone who is unfamiliar with how it works. It requires an explanation or walkthrough by someone familiar with it to understand.
- Feel free to assume any other reason. We love assumptions.

The source for the calc is available in this repository on a branch other than master (as of this writing, that branch is `stuff`). 
The calc is not an optional dependency because one of the fundamental features of Etterna is the calc itself, right next to the performance improvements.

**Comment by atoms118** [comment]
That's fair
In my opinion (not that it matters much), it would be better to keep the code in the main tree.

If the code being stolen is a huge concern, it could provided under a separate license that requires attribution. (Although taking a quick look at it, it seems too specialised to be copy-pasted into someone else's project, and someone willing to rewrite it from scratch would probably also be willing to check other branches for the source)

The reason I ask is because I was trying to package Etterna for Gentoo, which requires all packages to be compiled from source (in that although I technically can use the precompiled binary, it's not considered good practice and would never make it into official repos). I'm sure there are others with similar concerns (eg Arch users installing from the AUR, wierdos who compile everything from source manually for """fun""", etc)

**Comment by poco0317** [comment]
Part of the reason for putting the source on the repo in that branch after all of this time was so that it was easier to improve and work on for the future. The `stuff` branch at the moment is set up to output internal data from the calc in a displayable form ingame for testing so that we can make changes to the calc and see how to improve things. (In the past, changes to the calc were checked by reading massive lists of numbers output to a console.)

Ideally, that would be merged to master at some point in the future when the changes become "final" or in a publicly usable state.

**Comment by nico-abram** [comment]
I just wanna address this comment
"(Although taking a quick look at it, it seems too specialised to be copy-pasted into someone else's project, and someone willing to rewrite it from scratch would probably also be willing to check other branches for the source)"

I don't think it's about the code itself. It's about the *calc*, which isn't just the code. The code is an implelmentation of the calc. The calc (The way it works) is the actually valuable (?) thing afaik.

**Comment by MinaciousGrace** [comment]
"valuable" is probably not the right word but nick is correct

it's the difference between ``method to produce steel`` and ``steelworks that implements method to produce steel``
