### ISSUE TITLE
Make ScreenGameplaySyncMachine use player profile's modifiers instead of machine defaults

### ISSUE THREAD

**Issue by Jolomann** [etternagame/etterna#649]
The sync screen currently uses machine profile settings (defaults including C400, normal scroll etc.) which almost always differs from an actual player's settings. It also uses default machine noteskin. Changing this to using the player's own settings would be preferable, not just for convenience but also to make the audio sync wizard better for calibration

**Comment by poco0317** [comment]
I honestly feel like this is going to be harder than it should be, but its worth trying to do.

**Comment by Ulti-FD** [comment]
How about changing machine defaults to be the same as the profile mods on profile save? That is, if it doesn't add any (measurable) load time

**Comment by poco0317** [comment]
handled with low effort in gameplay rewrite by 930559503a410a5862c64b654565451a11c5cc50
basically (confirmed) i think it pulls the mods straight from the first profile you have instead of the essentially impossible to modify machine profile
i tested this with 5 profiles and with 0 profiles (clean setup) and it didnt crash
so its better than nothing

closed when merged
