### ISSUE TITLE
Viewing a previous score that was played with a different judge has incorrect info

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#670]
**Describe the bug**
If I view a J7 score, everything on the eval screen looks to be using J7 except the graph. Once you change the judge it updates the judgements, MA/PA, acc % accordingly.

**To Reproduce**
1. Make sure you're on J4/J5
2. View a J7 score
3. Note judgements, MA/PA, acc % are shown for J7
4. Change judge on eval screen
5. Score now correctly uses your current judge

**Expected behavior**
The initial judgement counts and MA/PA ratio when first viewing a score match your current judge.

**Screenshots**

Viewing a J7 score while using J4:
![image](https://user-images.githubusercontent.com/2302541/71141982-edd9fb00-21e3-11ea-925d-8b7ebcd6f04b.png)

Switch to another judge then go back to J4:
![image](https://user-images.githubusercontent.com/2302541/71142009-0a763300-21e4-11ea-87d6-3ad0f5902c6e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.67.0
 - 64bit

**Comment by poco0317** [comment]
Oversight due to laziness

**Comment by poco0317** [comment]
We have to assume that all site replays are J4, but I have this working clientside, kind of.

**Comment by poco0317** [comment]
Mitigated but not fully solved in hotfix by a series of commits.
Basically, when viewing a local replay the judge you start on in the eval screen is now the judge of the replay regardless of what you chose. So that works consistently. It doesn't match gameplay, but is more consistent with the score. This lets view eval make sense in a simpler way. At the same time, custom windows doesn't support this. So if you have custom windows on, this fix does not work.

Closed when merged.
