### ISSUE TITLE
Etternagame suggestion

### ISSUE THREAD

**Issue by 1NANI1** [etternagame/etterna#679]
1) Button Delete in order to delete pack in etternagame;
2)switch in settings for switching rendering between d3d and opengl( Someone is better suited to opengl for its graphics adapter and theme);
3) 
connect old cpp libraries for old pc (cross-platform). Some still use winxp, and cannot install new cpp libraries. Do not play them in stepmania:3
4)bind the rgb panel to change the color of the interface, it’s more convenient)
5)Voice chat in multiplayer

**Comment by poco0317** [comment]
I'll address these and ask that you edit and reopen this if you wish for them to remain.

1. We removed a functionality to delete songs from the game at some point because it seemed redundant with literally going to the song folder and deleting it yourself. It could be readded.
2. This makes sense to add, but would only be useful for Windows because d3d is not an option on Linux and Mac.
3. We don't support Windows XP, and neither should the rest of the world.
4. Done. I think?
5. Having a voice chat feature in a rhythm game would probably be something exclusive to us out of every rhythm game which is kind of interesting, but the utility or interest of that intersecting with the already low existing interest in multiplayer is not motivating. In addition, this is hard to implement, and if we did put it on a roadmap it would go behind a list of things to do so long it would literally never be done.
