### ISSUE TITLE
Fix SurviveSeconds in Etterna.xml

### ISSUE THREAD

**Issue by kangalioo** [etternagame/etterna#714]
Currently, "survive seconds is super broken" (quote from mina), meaning that although each score in the Etterna.xml has a SurviveSeconds entry, all those SurviveSeconds values are horribly wrong.

What SurviveSeconds _should_ be: the time duration that the player has survived (=not failed) in the chart for a given score, measured in seconds. In most cases, where the chart was successfully played from beginning to end, this is simply the duration of the chart (taking rates and other modifiers into account).

What SurviveSeconds _actually_ is: no idea.

It would be great if SurviveSeconds could be fixed because it is an invaluable metric for all kinds of analysis purposes. For example, the etterna-graph tool that I made uses it extensively, which is kinda a problem due to SurviveSeconds' brokenness. However, there's no way to replace SurviveSeconds that wouldn't add significant code complexity and performance hits to the program.

Also, keeping SurviveSeconds in this broken state is misleading to people utilizing their Etterna.xml data for whichever purpose: they think they can rely on SurviveSeconds as a metric and build cool software around it, and find out only later or even never that the metric they've based their work upon is actually horribly unreliable and broken.

Of course, it would be an option to remove SurviveSeconds entirely. If possible, I would prefer to avoid that though due to the usefulness of the metric (see first motivation paragraph).

**Comment by poco0317** [comment]
SurviveSeconds is replaced by PlayedSeconds in 0.71 and is saved per score. It is exactly the amount of real life time that spans between the moment the song is loaded until the score saves. As a result, the time may not be completely the same even though the same chart may be played twice due to loading time differences. This is to better reflect actual time spent in gameplay.
Legacy entries of SurviveSeconds are replaced by the chart length unless the score is a fail, in which case SurviveSeconds takes precendence. Unless it isn't available somehow. Every game startup, this number is recalculated.

relevant
f0951e1b122c7995cac12116edb698539aead0a2
