### ISSUE TITLE
Accuracy Doesn't Change with Score

### ISSUE THREAD

**Issue by WinterIsPretty** [etternagame/etterna#717]
**Describe the bug**
When you put up judge difficulty, it makes your score greater, whenever you make a score on the leaderboard it changes your accuracy to the score you made, not the actual accuracy you had.

**To Reproduce** 
1. turn up judge difficulty (both my life and judge diff are at 6)
2. play a map and get over 80% acc

**Expected behavior**
To display the score on the leaderboard but in between all the 95 percents, there will be a 86%

**Screenshots**
![image](https://user-images.githubusercontent.com/52920930/76884488-c37ff400-684b-11ea-8571-0964ebb0a8a6.png)
![image](https://user-images.githubusercontent.com/52920930/76884519-d09ce300-684b-11ea-9b24-4695aeafa506.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.68.1
 - 64bit

**Additional context**
The top score in the local leaderboard is also the one with a higher accuracy not score
I don't think my rank is affected by my score if it has less acc than my highest play

**Comment by TheROPFather** [comment]
This is intended behaviour.

**Comment by foxfire667** [comment]
So if I am reading this correctly, you are saying the expected behavior of increasing the judge would not be to normalize to the default percent, but instead show the raw percent for whatever judge you used? This would be incredibly confusing, and would make accuracy basically impossible to determine on a leaderboard. The percent you get is normalized to the default judge on EO, and also in client if you turn on the setting as of .68. 

It makes things a lot easier to read when the percents aren't wildly varying based on judge.

**Comment by poco0317** [comment]
All scores are normalized to J4 except the judgments sent to the site. Replay data is recorded at J4. At this point, your judge window is a personal preference and a local effect to apply.
This is intended behavior.

**Comment by WinterIsPretty** [comment]
I see, thanks for letting me know
