### ISSUE TITLE
Cannot build and run for x64 MacOS (Catalina etc)

### ISSUE THREAD

**Issue by lmiller1990** [etternagame/etterna#718]
**Describe the bug**
Cannot compile and run for x64 (macos)

**To Reproduce**

```
 cmake -DOPENSSL_ROOT_DIR="/usr/local/opt/openssl" -G "Ninja" -A x64
 cmake -DOPENSSL_ROOT_DIR="/usr/local/opt/openssl" -G "Xcode" -A x64
```

Both yield:

```
  Generator

    Ninja/Xcode

  does not support platform specification, but platform

    x64

  was specified.
```

The readme says Ninja *only* builds for x64, though.

**Expected behavior**
Builds for x64.

**Screenshots**

I tried running ninja w/o the x64 flag and it build this:

![image](https://user-images.githubusercontent.com/19196536/76955611-3a0d1680-695e-11ea-80bf-e271e8e1b1f3.png)

![image](https://user-images.githubusercontent.com/19196536/76955623-3e393400-695e-11ea-88fc-72f1e165af25.png)

Not sure what this means.

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/19196536/76955674-56a94e80-695e-11ea-9d9c-ad88161ccb23.png)

2017 macbook (not pro), latest catalina, x64 (they dropped x32 support).

**Additional context**

**Comment by jameskr97** [comment]
That's right! macOS will only build a 64-bit version since 32-bit support was dropped by Apple. Since only 64-bit will be build, you can completely omit that architecture `-A` tag.  And since you are getting a binary it looks like you are able to completely build the application, though something is definitely going wrong if you can't run it. Would you be able to upload the build log, or what you see on the terminal after running the `ninja` command, specifically any errors that show up?

Thanks for reporting this.

**Comment by lmiller1990** [comment]
Where can I get the build log? Is that `build.ninja`? I uploaded that one.

[build.txt](https://github.com/etternagame/etterna/files/4367448/build.txt)

**Comment by lmiller1990** [comment]
I tried to build it again. Here is the output:

```
cmake -DOPENSSL_ROOT_DIR="/usr/local/opt/openssl" -G "Ninja"
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error at CMakeLists.txt:14 (project):
  Generator

    Ninja

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/Users/lachlan/etterna/CMakeFiles/CMakeOutput.log".
```

**Comment by jameskr97** [comment]
@lmiller1990 So there are a few things you're bringing up here I want to be clear I'm understanding.

1. The issue you're having is that popup saying the binary is damaged. You are able to build and get the `Etterna.app`, but when it comes to running the program, it doesn't work. Is that correct?

2. The issues is happening with both Ninja and Xcode. Let's check Ninja first, since that one is what the issue was initally opened about. It looks like you are using the root directory as the build directory for the project. Would you be able to reset the working tree to head, then create a folder called `build`, then run that `make -DOPENSSL_ROOT_DIR="/usr/local/opt/openssl" -G "Ninja" ..` command inside that build folder? After that, you can run `ninja` in the build folder, and it should start compiling the application. When you do that please show me, not the full output, but the output before the command completes. It's not necessarily the git output I'm interested in, but more the build output, as that is where I believe you're issue is happening.

3. You also say Xcode isn't working, would you be able to generate an Xcode project, and run it in debug mode to see what happens?

Thanks for your help again.

**Comment by lmiller1990** [comment]
Hey, thanks for replying.

1. Yes, that's right. I can generate the binary (I am not sure how I did this when I opened the original issue, I thought I used ninja but now I'm thinking it was via Xcode)
2. I have been running my `make` commands from the root (not in build). I have a strong suspicion I was mistaken in my original issue. I make a directory called `build`, `cd` in there and ran this (with `make`. Should it be `cmake`? I put the `cmake` output after this:

## with `make` in the `build` directory

```
(master) $ make -DOPENSSL_ROOT_DIR=$(which openssl) -G "Ninja"
/Applications/Xcode.app/Contents/Developer/usr/bin/make: invalid option -- D
/Applications/Xcode.app/Contents/Developer/usr/bin/make: invalid option -- O
/Applications/Xcode.app/Contents/Developer/usr/bin/make: invalid option -- P
/Applications/Xcode.app/Contents/Developer/usr/bin/make: invalid option -- E
/Applications/Xcode.app/Contents/Developer/usr/bin/make: invalid option -- G
Usage: make [options] [target] ...
Options:
  -b, -m                      Ignored for compatibility.
  -B, --always-make           Unconditionally make all targets.
  -C DIRECTORY, --directory=DIRECTORY
                              Change to DIRECTORY before doing anything.
  -d                          Print lots of debugging information.
  --debug[=FLAGS]             Print various types of debugging information.
  -e, --environment-overrides
                              Environment variables override makefiles.
  -f FILE, --file=FILE, --makefile=FILE
                              Read FILE as a makefile.
  -h, --help                  Print this message and exit.
  -i, --ignore-errors         Ignore errors from commands.
  -I DIRECTORY, --include-dir=DIRECTORY
                              Search DIRECTORY for included makefiles.
  -j [N], --jobs[=N]          Allow N jobs at once; infinite jobs with no arg.
  -k, --keep-going            Keep going when some targets can't be made.
  -l [N], --load-average[=N], --max-load[=N]
                              Don't start multiple jobs unless load is below N.
  -L, --check-symlink-times   Use the latest mtime between symlinks and target.
  -n, --just-print, --dry-run, --recon
                              Don't actually run any commands; just print them.
  -o FILE, --old-file=FILE, --assume-old=FILE
                              Consider FILE to be very old and don't remake it.
  -p, --print-data-base       Print make's internal database.
  -q, --question              Run no commands; exit status says if up to date.
  -r, --no-builtin-rules      Disable the built-in implicit rules.
  -R, --no-builtin-variables  Disable the built-in variable settings.
  -s, --silent, --quiet       Don't echo commands.
  -S, --no-keep-going, --stop
                              Turns off -k.
  -t, --touch                 Touch targets instead of remaking them.
  -v, --version               Print the version number of make and exit.
  -w, --print-directory       Print the current directory.
  --no-print-directory        Turn off -w, even if it was turned on implicitly.
  -W FILE, --what-if=FILE, --new-file=FILE, --assume-new=FILE
                              Consider FILE to be infinitely new.
  --warn-undefined-variables  Warn when an undefined variable is referenced.
  -N OPTION, --NeXT-option=OPTION
                              Turn on value of NeXT OPTION.

This program built for i386-apple-darwin11.3.0
Report bugs to <bug-make@gnu.org>
(master) $
```

## with `cmake` in `build`

```
(master) $ cmake -DOPENSSL_ROOT_DIR=$(which openssl) -G "Ninja"
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error: The source directory "/Users/lachlan/etterna/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
(master) $
```

3. About Xcode, I am not opening the project in the Xcode app, I ran it from the command line using cmake and the `-G Xcode` flag.

Maybe I'm doing something obviously wrong? I am not very familiar with make or building C projects. I also realized I'm doing this on master - maybe that was the problem, I can try again on develop (should master be stable for macos x64?)

**Comment by jameskr97** [comment]
@lmiller1990 I would reccomend looking into C/C++ build systems and CMake as well. I think you are misunderstanding how it should be used. Here is the sparknotes:

What is important to understand, is that CMake is a "meta build system." CMake itself is not capable of compiling the source code into a binary you can run. You would use a C++ compiler like Clang, AppleClang (XCode), g++, or Visual Studio for that. What CMake is capable of doing is generating the project for XCode, Visual Studio, CodeBlocks, or whatever your preferred IDE/compiler is, so you can use those files to build the final binary.

In the first example you used, you are trying to directly build the project with `make`, before even generating the files needed to do so. You don't need those paramters with that make command, since `make` and `cmake` are not interchangable. I appears you're doing step 2 before doing step 1. Step 1 would be running CMake, which is necessary to get started compiling Etterna, then step 2, use the build system of choice to build the application. What you did in that second second was fine, but you didn't define the root directory. CMake needs to know where the root `CMakeLists.txt` file is in order to properly generate the project files. If you were to add `..` to the end of that command you used in the `with cmake in build` section, it would run just fine.

Please have a read of [the build instructions](https://github.com/etternagame/etterna/blob/master/Docs/Building.md) specifically the [Project Generation](https://github.com/etternagame/etterna/blob/master/Docs/Building.md#Project-Generation) section. I think some of the issues you're coming across might be addressed there. There are some sample commands that might help too.

**Comment by lmiller1990** [comment]
Hi @jameskr97, sorry I took a while to get back to you.

I may be misunderstanding - I do not have a background in C or `make` (or any of those kind of tools). I will try again on this weekend. Thanks for the help so far.

If I am on a mac, should it not be possible to write a bash script that will "do everything"? I would think most Catalina installations have more or less the same dependencies (or you can still them using said bash script, via `brew` etc.

**Comment by nico-abram** [comment]
@lmiller1990 I believe the point of cmake and other such build tools is specifically to avoid that. Because if we want to target 32 bit windows, 64 bit windows, same for linux and mac, have targets like the installer for windows and the dmg for mac, etc, and probably have many configurable compile flags and other build parameters, we would have to mantain a large number of bash/batch files (Or a fairly complex bash file and a bunch of batch files, or  python or something else script), and doing that is a lot of work. Also, adding a dependency if it correctly supports cmake is relatively simple (Or at least, it should be, in practice many times it isn't), while adding it otherwise would involve editing those scripts and the library could have arbitrary amounts of build-time complexity which we would need to port to our script. In short, yes, it is possible. It is just not the alternative currently used in this project (I personally have a .bat file to run cmake for this project for myself on windows, but that is mostly because I need to pass it the path to openssl and it's a PITA to type it all the time). 

I will also note I personally hate CMake, but it is what we currently have and it works. Moving to something else would be a huge effort, and it would need discussion, etc.

Did you find time to try again? You might want to join the development discord server in the readme, where you can ask for help and may get a response faster. Note that as far as I know the only active collaborator who currently owns a mac is Hidden, since if I recall correctly rop sold his.

**Comment by MinaciousGrace** [comment]
catalina build should be fixed now
