### ISSUE TITLE
Turn attacks might cause a back-end chain reaction

### ISSUE THREAD

**Issue by PCBoyGames** [etternagame/etterna#745]
### What is this about?

I made a testing file recently after remembering a simple but dangerous bug that has been seen throughout (if not all, then most of) SM5, and after talking about this with the developers of [SM5.3 Codename Outfox,](https://projectmoon.dance/index.php) it may have stuck around in an earlier SM. While I have yet to test it with Etterna, given fact it is based on the code from SM5, I feel as if this back-end chain reaction might still occur. [You can grab it here](https://cdn.discordapp.com/attachments/402810985070723074/701253517960151160/mirrorattacktest.zip) and try this out for yourselves.

### Here's a little bit of backstory to all of this.

The expected behavior of the file is that at the exact middle of the file, audibly marked with a sound alongside the metronome, the second half (in which the steps are copied and mirrored inside the note data) should correct itself to be about the same as the first half due to a Mirror attack being placed slightly after. However, in my tests with 5.3, this was not the case, as not only does the entire chart mirror, but sometimes the game freezes, and sometimes the counters are held off until near the end. Despite all of this oddity, here's one of the biggest ones: every single time, a seemingly random set of notes is able to be hit, but these do not count up on the judgement or combo counters, acting as if they were a pseudo fake note, although all notes in this file are real.

After playing through it on SM5.0.12, a member of the Moondance Discord sent in [a log which exposed many secretly underlying problems that it had ran through.](https://cdn.discordapp.com/attachments/586285188158586881/701229388842139678/crashinfo.txt) Many of the errors were predicted to have gone unnoticed during early SM5 development (which if my sources are right, would be up to nine years ago). Scrat and JoseValera, both SM5.3 developers, say they may have found a good starting point for their build using the crash log above, leading to where the attack is being handled as an initialization before the song starts. Because it was an initialization I was messing around with, I asked them if it's supposedly possible to counter this turn attack using a counteraction. Much to Jose's surprise, when he told me that "No" in an attack is an operator, therefore No Mirror should counter Mirror, that did not happen. The behavior was still the same as without a No Mirror attack.

### And now, on to you.

It's a complicated issue, but I am interested to see what you find with your build and how it compares to the log from 5.0.12 mentioned above. Maybe by just using a single attack, we could uncover many of the hidden workings that were never taken into consideration when coding in the attack system, and possibly more. I never thought I would have to do this, but however, this has been a problem for God knows how long and was never considered for fixing because it's such an uncommon bug scraper. If only there was a start to listing and tracking down every problem it caused, then maybe general functionality would be not as strange nor as difficult as it seems.

**Comment by MinaciousGrace** [comment]
iirc attacks were one of the first things removed entirely from this fork; they weren't really used in 4k kb meta and certainly weren't used at top level competition

this was because they altered the chart fundamentally in a way that invalidated comparison between scores (I don't actually know if the old .sm attack field was deterministic or not so technically this may not have been true for files that only used that, but it's not like anyone was interested in finding out)

attacks were also used for battle play (this was _definitely_ not deterministic since they were based on respective performances of the players during battle mode, though i guess that's kind of the point, but the scores would still have to have been invalidated), but we removed player 2 thus mooting the use case - and this was long before we created our own multiplayer server where theoretically attacks could have been used

given the cost benefit analysis of retaining and maintaining large systems of code that were not relevant to the direction we wanted to take the fork they were purged pretty early on, and this issue is a pretty clear indicator that this was a good decision for us

6e80f97136ded50a1f175a8e1904043175320aba probably removed most references to attacks, but if it didn't it was done prior to that and i can't find where with any quick commit searches

but thanks for the heads up 👍

**Comment by poco0317** [comment]
Tested given file ingame and didnt crash -- we don't have Attacks.
