### ISSUE TITLE
remove DrawHoldHeadForTapsOnSameRow, DrawRollHeadForTapsOnSameRow

### ISSUE THREAD

**Issue by Jousway** [etternagame/etterna#78]
might as well remove these 2 noteskin metrics
DrawHoldHeadForTapsOnSameRow=
DrawRollHeadForTapsOnSameRow=
seeing YOU FUCKING BROKE THEM

**Comment by xwidghet** [comment]
So let me get this straight. Instead of submitting an issue with a link to a noteskin using these metrics, you decide to write an angry message in an issue requesting that we remove it? That's like saying "I updated to the latest version and now no scores save properly. Please remove saving scores." I have no idea why you didn't even ask about it in discord considering we talk to you there.

I am closing this issue. Please open a new issue with this bug so that we can fix it.
