### ISSUE TITLE
Unexpected rank given after completing song

### ISSUE THREAD

**Issue by ZeeHatcher** [etternagame/etterna#809]
**Describe the bug**
After completing a song with the specified score in the screenshots below (single-digit "greats" and a single "good"), the SDG (Single Digit Greats) rank was given, instead of the expected MF (Miss Flag) rank.

**To Reproduce**
1. Achieve single-digit "greats" and a single "good" in a song.

**Expected behavior**
Since there was 1 "good" hit and my combo was broken, I expected the given rank to be MF, instead of SDG, since I believe MF is a worse rank than SDG, and the worse rank should be given.

**Screenshots**
Showing my hits and given rank:
![image](https://user-images.githubusercontent.com/25874627/85276972-31743100-b4b5-11ea-8f7d-8ee2bbc452f3.png)

Showing that the combo was broken:
![image](https://user-images.githubusercontent.com/25874627/85277035-4e106900-b4b5-11ea-90fd-06065983bf99.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Single Language
 - Version 1909 Build 18363.900
 - 64bit

**Additional context**
The version of Etterna that I have at the time of posting this is 0.69.1

**Comment by MinaciousGrace** [comment]
this is technically intended behavior; the highest achieved grade rank is intended to be doled out (colloquially most people talking about your score would use the format "sdg 1cb", even if they led with the cb count it's still not _not_ an sdg because of the cb), however mf's or missflags aren't really supposed to be given for any single combo breakers but are anyway

if the lowest rank were given there would have to be specific case handling for making mfc's not give pfc's, or just regular fc's instead, which would be silly

**Comment by poco0317** [comment]
the relevant code is here  and follows what mina lays out above https://github.com/etternagame/etterna/blob/ad135f144aff93b7979e68200574f0c7a1b6cbc2/Themes/Til%20Death/Scripts/ClearType.lua#L124-L148
