### ISSUE TITLE
Offset change prevent songs from being completed in subsequent plays.

### ISSUE THREAD

**Issue by TCHalogen** [etternagame/etterna#83]
Using Etterna 0.55.2 — if you make any sort of offset change to a song as it is playing and save it, the song becomes unable to be completed; the game fades as if the song has completed.

This bug is retroactive: if you close the game and restart it, those songs that were affected by this bug remain affected. Additionally, restoring the offset to what it was prior does not resolve the issue for the current session, or after the game is closed and reopened.

Here's a video showcasing this: https://www.youtube.com/watch?v=BuLdN1ONiMc

**Comment by MinaciousGrace** [comment]
yeah this is a known issue that has started to come up quite a lot in recent days, the solution is to manually reload the file from disk using ctrl shft r at music select on the file or to wipe the cache for the file from the cache dir and restart the game (more or less the same thing the cache is the problem)

at this point I am considering another small patch that will forcibly reload the file from disk after sync changes are applied along with other minor crash and bug fixes

originally I was waiting for 0.56 to fix it however that sort of ended up being ahead of schedule and in a weird way that may have pushed it back since there's an opportunity to increase the scope of updates

I haven't settled on a decision but I'm leaning toward another minor patch in a couple days

**Comment by TCHalogen** [comment]
Works for me temporarily; thanks a bunch for that, at least.

**Comment by MinaciousGrace** [comment]
fixed with 8eec96f5bc107c11aa57ff81c88989fb266bafc8
