### ISSUE TITLE
Please re-add filtering by highest song diff as an option in the filter window

### ISSUE THREAD

**Issue by TendrilChicken** [etternagame/etterna#840]
In 0.70.0 a bug was fixed that changed how song filtering works, in the changelog this was listed as `Filtering by MSD was specific to only the highest difficulty of a Song - #795`

I would like the old functionality added back in as an option in the filter window

In 0.69.1 this is what filtering looks like. While filtering was bugged, it was very convenient for avoiding lower difficulties and replaying the same song
https://streamable.com/qfj3a5

In 0.70.1 this is what filtering looks like. The bug is fixed and helps find a wider variety of songs but, as far as I can tell, there is no way to use the old functionality. Til Death has a highest only filter option, which while helpful (despite being bugged), isn't the same as the old filter functionality
https://streamable.com/i7jbm9

**Comment by bluebandit21** [comment]
Ok, to clarify this feature request here:
What Tendril is asking for is a new toggleable option to make only the highest-msd chart of a skill for a song show up as candidates for the filter.
(i.e. if a song had two charts, one overall MSD 6.7, the other 8.6, then with this hypothetical toggle enabled this song would not match a filter of overall 6-7, because the chart with the highest MSD for the overall skill would not match the filter)

This is notably *not* the same as the current highest-only option(which is admittedly confusingly named), which checks if a skillset is the highest MSD of *that particular chart*'s skillsets.

This toggle would only make sense within the context of a non-exclusive filter.

**Comment by poco0317** [comment]
done: #867
