### ISSUE TITLE
SQLite cache doesn't respect non-portable mode 

### ISSUE THREAD

**Issue by hexptr** [etternagame/etterna#850]
**Describe the bug**

Various issues around the cache:
* `Cache/cache.db` and `Cache/images.cache` are written out to the directory where the Etterna binary lives, not to the user's homedir (`~/.stepmania-5.0`).
* Game crashes if the `Cache` directory doesn't already exist 

I'm running on Linux.

**To Reproduce**
1. Start the game
2. Observe the cache files be written to the wrong place

**Expected behavior**
Expect the cache files to be written out to `~/.stepmania-5.0/Cache`

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Version 0.70.2
 - 64bit

I will look into this unless this is a known bug that someone already has context on.

**Comment by poco0317** [comment]
On one hand non-portable mode is almost entirely removed. On the other, it isn't completely forgotten because we keep having these long discussions that go nowhere talking about how every platform would be better or worse having portability treated in some specific way. 
I would prefer to remove this option.

**Comment by hexptr** [comment]
Ah, if the intention is to remove non-portable mode, then I will go ahead and
1. close this bug
2. rewrite the AUR package for Etterna on Arch Linux so that it copies the game to the player's homedir before startup, just to avoid having to use weird everyone-can-write-everywhere permissions
