### ISSUE TITLE
RandomMovies mode in Appearance Options gone?

### ISSUE THREAD

**Issue by ChasePines101** [etternagame/etterna#856]
Why is it removed in the new update? unless there is another way to play randommovies somewhere in this new one, but otherwise I really don't know why its removed.

**Comment by MinaciousGrace** [comment]
we already spent an hour discussing this and during that time i pointed you towards an lua solution and told you where you could get help with it

but if you want me to spell it out again, it was a unwieldy amount of code that was being dedicated to a purpose only you seem to care about and its existence was making other changes more difficult, so rather than spending time on modernizing it as well, it was removed
