### ISSUE TITLE
Deleting a favourites playlist causes a crash

### ISSUE THREAD

**Issue by shellgon26** [etternagame/etterna#857]
**Describe the bug**
Deleting a favourites playlist causes a crash

**To Reproduce**
1. Go toplaylist tab
2. Try to delte an empty favourites playlist
3. 

**Expected behavior**
Favourites playlist should be removed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windops
 - Version [e.g. 0.7.1]
 - 64bit

**Additional context**
[crashinfo.txt](https://github.com/etternagame/etterna/files/4944355/crashinfo.txt)

**Comment by MinaciousGrace** [comment]
soooooooooooooooooo this is kind of complicated and stupid, basically i wrapped the favorites into playlists in order to shortcut a way to make them a song group, but you can manipulate favorites independently from playlists which means any manipulation to the favorites playlist (or really just favorites) that _doesn't_ go through playlists (probably all of it, since it's more intuitive) needs to then redirect to also modify the favorites playlist.

currently only some of it does, and it was only to stop the most obvious crashes, and they were bandaids. I was able to reproduce this crash only once - ok i randomly fixed the crash while typing an explanation for why i couldn't fix it

_technically_ deleting the favorites playlist should unfavorite everything, however this is a destructive operation and modifying playlists invokes a save (because people kept forgetting to do this after making them), plus there are other ways to do this, so i'm going to _also_ disable the delete playlist button for favorites (which is how the behavior works with charts in it as well)

e90d6164dfb533e08aea7fca53d88be7ba99e6be
