### ISSUE TITLE
Mine bug during replay

### ISSUE THREAD

**Issue by Brankale** [etternagame/etterna#919]
**Describe the bug**
If during a replay a mine is hit, the number of NPS (notes per second) goes through the roof (in some cases thousands of NPS) and the score is affected negativly (for example if your score was 98 after you hit a mine it goes at for example 67).

**To Reproduce**
Play a chart and hit a mine. Watch the replay.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2004
 - 64bit

**Comment by poco0317** [comment]
could not reproduce but ive had this happen and seen it happen and manifest in a lot of different ways

i reproduced a form of it where a mine hit was basically expecting to be judged twice and then was not judged twice (because this is impossible) so blah blah blah
basically i think i fixed it
3f5ce78ecb0b971dc72d40a6481c900c7761d339
