### ISSUE TITLE
Etterna crashes when the restart key is pressed during audio calibration

### ISSUE THREAD

**Issue by BlueRayEnder** [etternagame/etterna#927]
**Describe the bug**
Etterna crashes when the restart key is pressed during audio calibration

**To Reproduce**
1. Go to 'calibrate audio sync'
2. Click the restart gameplay key during calibration
3. It may ask you whether save the change or not(sometime will not)
4. The game crashes

**Expected behavior**
the calibration restart or directly exit to menu

 - OS: window
 - Version 0.70.3
 - 64bit

**Comment by poco0317** [comment]
easily reproducible

**Comment by SaundersCox** [comment]
Same issue 

**Describe the bug**
Calibrate Audio song crashes when hitting restart

**To Reproduce**
Steps to reproduce the behavior:
1. Options -> Input -> Calibrate Audio Sync
2. Hit the assigned hotkey for restart

**Expected behavior**
The song would restart appropriately

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10 Education
 - Version 2004
 - 64bit

**Additional context**
CPU: AMD Ryzen 5 3600 6-Core Processor
GPU: NVIDIA GeForce GTX 960

**Comment by poco0317** [comment]
fixed for 0.71 83b2fc1b17a868d3b1563e2d42521b4480ac7a3c
