### ISSUE TITLE
SurviveSeconds set to 0 when converted to PlayedSeconds in 0.71.0

### ISSUE THREAD

**Issue by g-robertson** [etternagame/etterna#942]
**Describe the bug**
Conversion of Etterna.xml from 0.70.3 to develop 0.71.0 currently sets all SurviveSeconds values in 0.70.3xml to 0.00000 when changed to PlayedSeconds

**To Reproduce**
Load a 0.70.3 Etterna.xml into 0.71.0

**Expected behavior**
Set PlayedSeconds to what SurviveSeconds was

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2004
 - 64bit

**Comment by poco0317** [comment]
I believe this was intended, because when adjusting for rates the previous value was wrong resulting in the gameplay seconds at the top of the xml to be wrong, so we are trying to replace it with something that isn't broken.
That being said if you're on a develop version like you are now and now your xml has numbers in it that are bad that is your own fault. Hope you have a backup :)

**Comment by poco0317** [comment]
anyways
fixed calculation e4490934381872de7455f9d685057db3af640666
fixed number loading f0951e1b122c7995cac12116edb698539aead0a2
