### ISSUE TITLE
Can't install packs on linux.

### ISSUE THREAD

**Issue by Ether-al** [etternagame/etterna#967]
**Describe the bug**
Etterna dowloads the packs, but does not install them, with the warning : WARNING: RageUtil/File/RageFileDriverZip.cpp:145: Couldn't open Cache/Downloads/pack.zip: couldn't find end of central directory record,

**To Reproduce**
1. Build and configure etterna with CMake
2. Launch the game
3. Download a pack

 -  OS: Artix Linux (runit)
 - Version: 0.70.3
 - 64bit

**Comment by nico-abram** [comment]
Could you share one of the pack files that gave you the error here? Did you try manually extracting it? I'm curious if the problem is the files are corrupted and not downloaded/saved properly, or if the problem is with extraction (Where my initial random guess would be some kind of file permission problem)

**Comment by Ether-al** [comment]
> Could you share one of the pack files that gave you the error here? Did you try manually extracting it? I'm curious if the problem is the files are corrupted and not downloaded/saved properly, or if the problem is with extraction (Where my initial random guess would be some kind of file permission problem)

Seems like the problem is the pack files itself, I tried extracting them manually and it failed, most likely being that it's corrupted. Pack files in question is the bundles offered to the player if there is no songs on the respective folder, I've tested the beginner, novice, and the intermediate bundles so far.

**Comment by poco0317** [comment]
In the current client, some bundle downloads may fail due to leading to dead links (because the client points to the mirrors only for bundle downloads and the mirrors arent guaranteed to be alive since they are google drive links) and as a result when the client hits the dead link you get garbage

So when it extracts you get nothing
I call this fixed/not a client issue
In 0.71 bundle downloads will not be forced to mirror downloads, but can be changed to do so via lua. If possible if you want to help us (if not someone is going to do it eventually), investigate and determine exactly which packs in the bundles have mirror links which do not work. For now, your alternative is to open the pack downloader, go to the bundles page, and click a bundle to filter the pack list to only the packs in that bundle - then you can click the download link instead of the mirror link.
